version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  deploy_master:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm start
workflows:
    build-and-test:
      jobs:
        - build_and_test
        - deploy_master:
            filters:
              branches:
                only:
                  - master
            requires:
              - build_and_test
